#!/usr/bin/env python3
"""GIMP CLI - Stateful command-line interface for raster image processing.

Generated by CLI-Anything methodology (7-phase pipeline).
Uses Pillow as primary engine with optional GIMP batch mode fallback.
"""

import json
import os
import sys
import functools

import click

from cli_anything.gimp.core.session import Session
from cli_anything.gimp.core import project as proj_mod
from cli_anything.gimp.core import layers as layer_mod
from cli_anything.gimp.core import filters as filter_mod
from cli_anything.gimp.core import canvas as canvas_mod
from cli_anything.gimp.core import media as media_mod
from cli_anything.gimp.core import export as export_mod
from cli_anything.gimp.utils.repl_skin import ReplSkin

_session = Session()
_json_output = False
_repl_mode = False


def output(data):
    """Print output as JSON or human-readable."""
    if _json_output:
        click.echo(json.dumps(data, indent=2, default=str))
    else:
        if isinstance(data, dict):
            if not data.get("ok", True):
                click.secho(f"Error: {data.get('error', 'Unknown error')}", fg="red")
                return
            for key, val in data.items():
                if key == "ok":
                    continue
                if isinstance(val, (dict, list)):
                    click.echo(f"  {key}: {json.dumps(val, indent=2, default=str)}")
                else:
                    click.echo(f"  {key}: {val}")
        else:
            click.echo(data)


def handle_error(f):
    """Decorator for consistent error handling."""
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        try:
            return f(*args, **kwargs)
        except FileNotFoundError as e:
            output({"ok": False, "error": f"File not found: {e}"})
        except json.JSONDecodeError as e:
            output({"ok": False, "error": f"Invalid JSON: {e}"})
        except Exception as e:
            output({"ok": False, "error": str(e)})
    return wrapper


def require_project(f):
    """Decorator that ensures a project is loaded."""
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        if _session.project is None:
            output({"ok": False, "error": "No project loaded. Use 'project new' or 'project open' first."})
            return
        return f(*args, **kwargs)
    return wrapper


# ─── Main Group ───────────────────────────────────────────────────────────

@click.group(invoke_without_command=True)
@click.option("--json", "use_json", is_flag=True, help="Output in JSON format for agent consumption.")
@click.option("--project", "-p", "project_path", help="Auto-load project file.")
@click.version_option("1.0.0", prog_name="cli-anything-gimp")
@click.pass_context
def main(ctx, use_json, project_path):
    """GIMP CLI - Raster image processing via CLI.

    A stateful CLI for image editing with layers, filters, canvas
    manipulation, and export. Uses Pillow as primary engine with
    optional GIMP batch mode fallback.
    """
    global _json_output
    _json_output = use_json

    if project_path:
        result = proj_mod.open_project(project_path)
        if result["ok"]:
            _session.project = result["project"]
            _session.project_path = project_path

    if ctx.invoked_subcommand is None:
        _start_repl()


# ─── REPL ─────────────────────────────────────────────────────────────────

def _start_repl():
    """Start interactive REPL mode."""
    global _repl_mode
    _repl_mode = True
    skin = ReplSkin()
    skin.print_banner()

    repl_commands = {
        "help": "Show this help",
        "quit/exit": "Exit REPL",
        "undo": "Undo last action",
        "redo": "Redo last undone action",
        "history": "Show undo history",
        "save": "Save current project",
        "info": "Show project info",
        "layers": "List layers",
        "filters": "List applied filters",
        "canvas": "Show canvas info",
    }

    while True:
        try:
            line = skin.get_input()
            if line is None:
                break
            line = line.strip()
            if not line:
                continue
            if line in ("quit", "exit", "q"):
                skin.info("Session ended.")
                break
            elif line == "help":
                skin.help(repl_commands)
            elif line == "undo":
                result = _session.undo()
                output(result)
            elif line == "redo":
                result = _session.redo()
                output(result)
            elif line == "history":
                output({"ok": True, "history": _session.list_history()})
            elif line == "save":
                result = _session.save_session()
                output(result)
            elif line == "info":
                if _session.project:
                    output(proj_mod.get_project_info(_session.project))
                else:
                    skin.warning("No project loaded.")
            elif line == "layers":
                if _session.project:
                    output(layer_mod.list_layers(_session.project))
                else:
                    skin.warning("No project loaded.")
            elif line == "filters":
                if _session.project:
                    output(filter_mod.list_filters(_session.project))
                else:
                    skin.warning("No project loaded.")
            elif line == "canvas":
                if _session.project:
                    output(canvas_mod.get_canvas_info(_session.project))
                else:
                    skin.warning("No project loaded.")
            else:
                # Try to parse as a CLI subcommand
                try:
                    args = line.split()
                    main(args, standalone_mode=False)
                except SystemExit:
                    pass
                except click.exceptions.UsageError as e:
                    skin.error(str(e))
        except KeyboardInterrupt:
            print()
            continue


# ─── Project Commands ─────────────────────────────────────────────────────

@main.group()
def project():
    """Create, open, and manage image projects."""
    pass


@project.command("new")
@click.option("--name", "-n", default="untitled", help="Project name.")
@click.option("--width", "-w", default=1920, type=int, help="Canvas width.")
@click.option("--height", "-h", default=1080, type=int, help="Canvas height.")
@click.option("--dpi", default=72, type=int, help="Canvas DPI.")
@click.option("--mode", default="RGB", type=click.Choice(["RGB", "RGBA", "L", "CMYK"]))
@click.option("--profile", type=click.Choice(list(proj_mod.PROFILES.keys())), help="Use a preset profile.")
@click.option("--output", "-o", help="Output file path.")
@handle_error
def project_new(name, width, height, dpi, mode, profile, output_path=None):
    """Create a new image project."""
    result = proj_mod.create_project(name, width, height, dpi, mode, profile, output_path)
    if result["ok"]:
        _session.project = result["project"]
        _session.project_path = result["path"]
        _session.snapshot("Created project")
    output(result)


@project.command("open")
@click.argument("path")
@handle_error
def project_open(path):
    """Open an existing project file."""
    result = proj_mod.open_project(path)
    if result["ok"]:
        _session.project = result["project"]
        _session.project_path = result["path"]
        _session.snapshot("Opened project")
    output(result)


@project.command("save")
@click.option("--output", "-o", help="Save to a different path.")
@handle_error
@require_project
def project_save(output_path=None):
    """Save the current project."""
    path = output_path or _session.project_path
    result = proj_mod.save_project(_session.project, path)
    output(result)


@project.command("info")
@handle_error
@require_project
def project_info():
    """Show project details."""
    output(proj_mod.get_project_info(_session.project))


@project.command("profiles")
@handle_error
def project_profiles():
    """List available canvas presets."""
    output({"ok": True, "profiles": proj_mod.list_profiles()})


# ─── Layer Commands ───────────────────────────────────────────────────────

@main.group()
def layer():
    """Add, remove, and manage layers."""
    pass


@layer.command("add")
@click.option("--name", "-n", required=True, help="Layer name.")
@click.option("--type", "layer_type", default="solid", type=click.Choice(["solid", "image"]))
@click.option("--color", "-c", default="#FFFFFF", help="Fill color (solid layers).")
@click.option("--opacity", default=1.0, type=float, help="Opacity 0.0-1.0.")
@click.option("--position", type=int, help="Stack position.")
@handle_error
@require_project
def layer_add(name, layer_type, color, opacity, position):
    """Add a new layer."""
    _session.snapshot(f"Before add layer: {name}")
    result = layer_mod.add_layer(_session.project, name, layer_type, color, opacity, position=position)
    output(result)


@layer.command("add-file")
@click.argument("path")
@click.option("--name", "-n", help="Layer name.")
@click.option("--opacity", default=1.0, type=float)
@click.option("--position", type=int)
@handle_error
@require_project
def layer_add_file(path, name, opacity, position):
    """Add a layer from an image file."""
    _session.snapshot(f"Before add file layer: {path}")
    result = layer_mod.add_from_file(_session.project, path, name, opacity, position)
    output(result)


@layer.command("remove")
@click.argument("layer_id")
@handle_error
@require_project
def layer_remove(layer_id):
    """Remove a layer by ID."""
    _session.snapshot(f"Before remove layer: {layer_id}")
    result = layer_mod.remove_layer(_session.project, layer_id)
    output(result)


@layer.command("duplicate")
@click.argument("layer_id")
@click.option("--name", "-n", help="Name for the copy.")
@handle_error
@require_project
def layer_duplicate(layer_id, name):
    """Duplicate a layer."""
    _session.snapshot(f"Before duplicate layer: {layer_id}")
    result = layer_mod.duplicate_layer(_session.project, layer_id, name)
    output(result)


@layer.command("move")
@click.argument("layer_id")
@click.argument("position", type=int)
@handle_error
@require_project
def layer_move(layer_id, position):
    """Move a layer to a new stack position."""
    _session.snapshot(f"Before move layer: {layer_id}")
    result = layer_mod.move_layer(_session.project, layer_id, position)
    output(result)


@layer.command("set")
@click.argument("layer_id")
@click.argument("prop")
@click.argument("value")
@handle_error
@require_project
def layer_set(layer_id, prop, value):
    """Set a layer property (name, opacity, visible, blend_mode, offset_x, offset_y, color)."""
    _session.snapshot(f"Before set layer property: {layer_id}.{prop}")
    if prop in ("opacity", "offset_x", "offset_y"):
        value = float(value)
    elif prop == "visible":
        value = value.lower() in ("true", "1", "yes")
    result = layer_mod.set_layer_property(_session.project, layer_id, prop, value)
    output(result)


@layer.command("get")
@click.argument("layer_id")
@handle_error
@require_project
def layer_get(layer_id):
    """Get layer details."""
    result = layer_mod.get_layer(_session.project, layer_id)
    output(result)


@layer.command("list")
@handle_error
@require_project
def layer_list():
    """List all layers in the project."""
    result = layer_mod.list_layers(_session.project)
    output(result)


@layer.command("flatten")
@handle_error
@require_project
def layer_flatten():
    """Flatten all layers into one."""
    _session.snapshot("Before flatten")
    result = layer_mod.flatten_layers(_session.project)
    output(result)


@layer.command("merge-down")
@click.argument("layer_id")
@handle_error
@require_project
def layer_merge_down(layer_id):
    """Merge a layer with the one below it."""
    _session.snapshot(f"Before merge-down: {layer_id}")
    result = layer_mod.merge_down(_session.project, layer_id)
    output(result)


# ─── Canvas Commands ──────────────────────────────────────────────────────

@main.group()
def canvas():
    """Resize, scale, crop, and configure the canvas."""
    pass


@canvas.command("resize")
@click.option("--width", "-w", required=True, type=int)
@click.option("--height", "-h", required=True, type=int)
@click.option("--anchor", default="center", type=click.Choice(list(canvas_mod.ANCHOR_MAP.keys())))
@handle_error
@require_project
def canvas_resize(width, height, anchor):
    """Resize canvas with anchor positioning."""
    _session.snapshot("Before canvas resize")
    result = canvas_mod.resize_canvas(_session.project, width, height, anchor)
    output(result)


@canvas.command("scale")
@click.option("--width", "-w", required=True, type=int)
@click.option("--height", "-h", required=True, type=int)
@handle_error
@require_project
def canvas_scale(width, height):
    """Scale canvas and layers proportionally."""
    _session.snapshot("Before canvas scale")
    result = canvas_mod.scale_canvas(_session.project, width, height)
    output(result)


@canvas.command("crop")
@click.option("--left", required=True, type=int)
@click.option("--top", required=True, type=int)
@click.option("--right", required=True, type=int)
@click.option("--bottom", required=True, type=int)
@handle_error
@require_project
def canvas_crop(left, top, right, bottom):
    """Crop canvas to a bounding box."""
    _session.snapshot("Before canvas crop")
    result = canvas_mod.crop_canvas(_session.project, left, top, right, bottom)
    output(result)


@canvas.command("mode")
@click.argument("mode", type=click.Choice(["RGB", "RGBA", "L", "CMYK"]))
@handle_error
@require_project
def canvas_mode(mode):
    """Set canvas color mode."""
    _session.snapshot("Before set mode")
    result = canvas_mod.set_mode(_session.project, mode)
    output(result)


@canvas.command("dpi")
@click.argument("dpi", type=int)
@handle_error
@require_project
def canvas_dpi(dpi):
    """Set canvas DPI."""
    _session.snapshot("Before set DPI")
    result = canvas_mod.set_dpi(_session.project, dpi)
    output(result)


@canvas.command("info")
@handle_error
@require_project
def canvas_info():
    """Show canvas details."""
    result = canvas_mod.get_canvas_info(_session.project)
    output(result)


# ─── Filter Commands ──────────────────────────────────────────────────────

@main.group("filter")
def filter_group():
    """Apply, remove, and manage image filters."""
    pass


@filter_group.command("add")
@click.argument("filter_name")
@click.option("--layer", "layer_id", help="Apply to specific layer (default: canvas).")
@click.option("--param", "-p", multiple=True, help="Filter params as key=value.")
@handle_error
@require_project
def filter_add(filter_name, layer_id, param):
    """Add a filter to the project or a layer."""
    _session.snapshot(f"Before add filter: {filter_name}")
    params = {}
    for p in param:
        if "=" in p:
            k, v = p.split("=", 1)
            try:
                v = float(v)
                if v == int(v):
                    v = int(v)
            except ValueError:
                pass
            params[k] = v
    target = "layer" if layer_id else "canvas"
    result = filter_mod.add_filter(_session.project, filter_name, target, layer_id, **params)
    output(result)


@filter_group.command("remove")
@click.argument("filter_id")
@click.option("--layer", "layer_id", help="Remove from specific layer.")
@handle_error
@require_project
def filter_remove(filter_id, layer_id):
    """Remove a filter by ID."""
    _session.snapshot(f"Before remove filter: {filter_id}")
    result = filter_mod.remove_filter(_session.project, filter_id, layer_id)
    output(result)


@filter_group.command("set")
@click.argument("filter_id")
@click.argument("param")
@click.argument("value")
@click.option("--layer", "layer_id")
@handle_error
@require_project
def filter_set(filter_id, param, value, layer_id):
    """Update a filter parameter."""
    try:
        value = float(value)
        if value == int(value):
            value = int(value)
    except ValueError:
        pass
    _session.snapshot(f"Before set filter param: {filter_id}.{param}")
    result = filter_mod.set_filter_param(_session.project, filter_id, param, value, layer_id)
    output(result)


@filter_group.command("list")
@click.option("--category", "-c", help="Filter by category.")
@click.option("--available", is_flag=True, help="Show all available filters.")
@handle_error
def filter_list(category, available):
    """List applied or available filters."""
    if available:
        result = filter_mod.list_filters(category=category)
    else:
        if _session.project is None:
            output({"ok": False, "error": "No project loaded."})
            return
        result = filter_mod.list_filters(_session.project, category)
    output(result)


# ─── Media Commands ───────────────────────────────────────────────────────

@main.group()
def media():
    """Inspect and manage media files."""
    pass


@media.command("probe")
@click.argument("path")
@handle_error
def media_probe(path):
    """Inspect an image file (dimensions, EXIF, format)."""
    result = media_mod.probe_image(path)
    output(result)


@media.command("list")
@handle_error
@require_project
def media_list():
    """List all media files in the project."""
    result = media_mod.list_media_in_project(_session.project)
    output(result)


@media.command("check")
@handle_error
@require_project
def media_check():
    """Validate all media file references."""
    result = media_mod.check_media(_session.project)
    output(result)


@media.command("histogram")
@click.argument("path")
@handle_error
def media_histogram(path):
    """Get color histogram for an image."""
    result = media_mod.get_image_histogram(path)
    output(result)


# ─── Export Commands ──────────────────────────────────────────────────────

@main.group("export")
def export_group():
    """Render and export project to image files."""
    pass


@export_group.command("render")
@click.argument("output_path")
@click.option("--preset", default="png", type=click.Choice(list(export_mod.EXPORT_PRESETS.keys())))
@click.option("--quality", type=int, help="Override quality setting.")
@handle_error
@require_project
def export_render(output_path, preset, quality):
    """Render project to an image file."""
    result = export_mod.render(_session.project, output_path, preset, quality)
    output(result)


@export_group.command("presets")
@handle_error
def export_presets():
    """List available export presets."""
    result = export_mod.list_presets()
    output(result)


# ─── Session Commands ─────────────────────────────────────────────────────

@main.group()
def session():
    """Manage session state, undo/redo."""
    pass


@session.command("undo")
@handle_error
def session_undo():
    """Undo the last action."""
    result = _session.undo()
    output(result)


@session.command("redo")
@handle_error
def session_redo():
    """Redo the last undone action."""
    result = _session.redo()
    output(result)


@session.command("history")
@handle_error
def session_history():
    """Show undo/redo history."""
    output({"ok": True, "history": _session.list_history()})


@session.command("save")
@click.option("--path", help="Save to a specific path.")
@handle_error
def session_save(path):
    """Save session to disk."""
    result = _session.save_session(path)
    output(result)


@session.command("load")
@click.argument("path")
@handle_error
def session_load(path):
    """Load session from disk."""
    result = _session.load_session(path)
    output(result)


# ─── Draw Commands ────────────────────────────────────────────────────────

@main.group()
def draw():
    """Drawing operations (via GIMP batch mode)."""
    pass


@draw.command("create")
@click.option("--width", "-w", default=800, type=int)
@click.option("--height", "-h", default=600, type=int)
@click.option("--output", "-o", required=True, help="Output file path.")
@click.option("--bg", default="white", help="Background color.")
@handle_error
def draw_create(width, height, output, bg):
    """Create a blank image via GIMP backend."""
    from cli_anything.gimp.utils.gimp_backend import create_and_export
    result = create_and_export(width, height, output, bg)
    output(result)


@draw.command("apply-filter")
@click.argument("input_path")
@click.argument("output_path")
@click.option("--filter", "filter_name", required=True, help="GIMP filter name.")
@click.option("--param", "-p", multiple=True, help="Filter params as key=value.")
@handle_error
def draw_apply_filter(input_path, output_path, filter_name, param):
    """Apply a GIMP-native filter via batch mode."""
    from cli_anything.gimp.utils.gimp_backend import apply_filter_and_export
    params = {}
    for p in param:
        if "=" in p:
            k, v = p.split("=", 1)
            try:
                v = float(v)
            except ValueError:
                pass
            params[k] = v
    result = apply_filter_and_export(input_path, output_path, filter_name, params)
    output(result)


# ─── REPL Command ─────────────────────────────────────────────────────────

@main.command()
def repl():
    """Enter interactive REPL mode."""
    _start_repl()


if __name__ == "__main__":
    main()
